config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
    root 'static_pages#home'
  
    #Devise routes
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }
    
    resources :users, only: [:show, :index]
    resources :tags, only: [:index, :show, :create]
    resources :channels, only: [:index, :show]
    
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates_uniqueness_of :title
    
    has_many :user_channel_tag_relationships
    has_many :users, -> { distinct }, through: :user_channel_tag_relationships
    has_many :channels, -> { distinct }, through: :user_channel_tag_relationships
    
    def self.all_with_channels_count
            Tag.joins(:user_channel_tag_relationships)
            .group("tags.title")
            .pluck('tags.title, COUNT(user_channel_tag_rels.channel_id) as channels_count')
            .to_h
    end
    
    def self.all_with_channels
        Tag.joins(:channels)
            .pluck("tags.title, channels.uid")
            .inject({}) { |hash, columns|
                if hash[columns[0]]
                    hash[columns[0]] << columns[1]
                else
                    hash[columns[0]] = [columns[1]]
                end
                hash
            }
    end
    
    def self.all_with_channels_hash
        tags = Tag.all_with_channels
        youtube_api = YoutubeApi.new
        
        channels = youtube_api.get_channels(tags.values.flatten)
        
        tags_with_channels, chans = User.new.split_infos(tags, channels)
        
        tags_with_channels
    end
end

app/models/youtube/tag.rb
class Youtube::Tag < ApplicationRecord
    validates_uniqueness_of :title
    
    has_many :user_channel_tag_relationships
    has_many :users, through: :user_channel_tag_relationships
    has_many :channels, through: :user_channel_tag_relationships, source: :youtube_channel
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    
    before_action :set_tag, only: [:show]
    
    def create
        if(user_signed_in?)
            error_messages = []
            tag_params['tag_titles'].each do |tag_title|
                tag = Tag.find_or_create_by(title: tag_title)
                channel = Channel.find_or_create_by(uid: tag_params['channel_uid'])
            
                relation = UserChannelTagRelationship.new(tag: tag, channel: channel, user: current_user)
                if(!relation.save)
                    error_messages += relation.errors.full_messages
                end
            end
            
            if(error_messages.empty?)
                redirect_to user_path(current_user)
            else
                redirect_to user_path(current_user), alert: error_messages.join("\n")
            end
            
        else
            redirect_to user_path(current_user), alert: "You must be signed in."
        end
    end
    
    def index
        
    end
    
    def show
        channel_uids = @tag.channels.pluck(:uid)
        youtube_api = YoutubeApi.new
        @channels = youtube_api.get_channels(channel_uids)
        
        # /!\ Might be very long ?
        @videos = @channels.values.map{ |channel| 
            youtube_api.get_playlist_videos(channel.upload_playlist_id).values
        }.flatten
    end
    
    private
    
        def tag_params
            params.permit(:channel_uid, tag_titles: [])
        end
        
        def set_tag
            @tag = Tag.find(params[:id]) || Tag.find(params[:tag_id])
        end
end

app/views/tags/_add_tags_button.html.erb
<% channel ||= {} %>

<button type="button" class="btn btn-primary pl-1 pr-1 pb-1 pt-0" data-toggle="modal" data-target="#<%=channel.uid%>_modal">
  + tags
</button>

<%= render partial: "tags/tags_modal", locals: { channel: channel } %>

app/views/tags/_tag.html.erb
<% channel ||= OpenStruct.new(uid: "") %>
<% tag_title ||= "" %>
<% channels_count ||= 0 %>
<% klass ||= "" %>
<% no_link = no_link.nil? ? false : no_link %>

<% title_with_count = channels_count > 0 ? "#{tag_title} (#{channels_count})" : tag_title %>


<% if no_link %>
    <div class="btn btn-secondary pl-1 pr-1 pb-1 pt-0"><%= title_with_count %></div>
    
<% else %>

    <%= link_to "#", class: "btn btn-secondary pl-1 pr-1 pb-1 pt-0 add_tag #{klass}", "attr-uid": channel.uid, "attr-title": tag_title, "attr-channels-count": channels_count do %>
        <div class="tag_text"><%= title_with_count %></div>
        <%# input type="hidden" name="tag_titles[]" id="tag_titles" value="Test Tag" %>
    <% end %>
    
<% end %>

app/views/tags/_tag_with_channels.html.erb
<% tag_title ||= "Tag Title" %>
<% channels ||= [] %>
<% no_link ||= false %>

<div class="tag_with_channels_block pl-3 pr-3 mt-1 mb-3">
    <%= link_to tag_path(Tag.find_by(title: tag_title)) do %>
        <h2>
            <%= image_tag "https://image.flaticon.com/icons/svg/26/26025.svg", class: "img-fluid", style: "height: 1em" %>
            <%= tag_title %> <small>(<%= channels.count %>)</small>
        </h2>
    <% end %>
    
    <%= render partial: "youtube/channels", locals: { channels: channels, no_link: no_link } %>
</div>

app/views/tags/_tags.html.erb
<% tags ||= {} %>
<% channel ||= OpenStruct.new(uid: "") %>
<% no_link = no_link.nil? ? false : no_link %>

<% tags.each do |tag_title, channels_count| %>
    <%= render partial: "tags/tag", locals: {channel: channel, tag_title: tag_title, channels_count: channels_count, no_link: no_link} %>
<% end %>

app/views/tags/_tags_modal.html.erb
<% channel ||= {} %>

<div class="modal fade" id="<%=channel.uid%>_modal" tabindex="-1" role="dialog" aria-labelledby="<%=channel.uid%>ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag tags_path, method: :post do %>
        
        <div class="modal-header">
            <h5 class="modal-title" id="<%=channel.uid%>ModalLabel">
                Add tags to this channel
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-sm-4 pr-1">
                    <%= link_to "https://www.youtube.com/channel/#{channel.uid}" do %>
                        <%= image_tag channel.thumbnail_url, class: "img-fluid rounded" %>    
                    <% end %>
                </div>
                <div class="col-sm-8 pl-1">
                    <%= link_to "https://www.youtube.com/channel/#{channel.uid}" do %>
                        <strong><%= channel.title.truncate(30) %></strong>
                    <% end %>
                    <div class="tags_fields" attr-uid="<%= channel.uid %>">
                        <%= hidden_field_tag('channel_uid', channel.uid)%>
                        <%= render partial: "tags/tags", locals: { tags: @channels_with_tags[channel.uid], no_link: true } %>
                        <%= render partial: "tags/tag", locals: {klass: "tag_model"} %>
                    </div>
                </div>
            </div>
            
            <div class="mt-2">
                <%= text_field_tag 'title_field', nil, placeholder: "Create a new Tag", class: "title_field", "attr-uid": channel.uid %>
                <%= link_to "+", "#", class: "btn btn-secondary pl-2 pr-2 pb-1 pt-1 add_new_tag", "attr-uid": channel.uid %>
            </div>
            
            <div class="my_tags" attr-uid="<%= channel.uid %>">
                <strong>My other tags</strong><br />
                <%= render partial: "tags/tags", locals: { tags: @my_tags_with_count.except(*@channels_with_tags[channel.uid]), channel: channel } %>
                
                <% if @other_tags_with_count.present? %>
                    <br />
                    <strong>All other existing tags</strong><br />
                    <%= render partial: "tags/tags", locals: { tags: @other_tags_with_count, channel: channel } %>
                <% end %>
            </div>
        </div>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag 'Update Tags', class: "btn btn-primary" %>
        </div>
          
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_tags_with_channels.html.erb
<% tags ||= {} %>
<% no_link ||= false %>

<% tags.each do |tag_title, channels| %>
    <%= render partial: "tags/tag_with_channels", locals: { tag_title: tag_title, channels: channels, no_link: no_link } %>
<% end %>

app/views/tags/show.html.erb
<% sorted_videos = @videos.sort_by{ |video| video.published_at }.reverse.take(12) %>

<%#= render partial: "youtube/channels", locals: { channels: @channels.values } %>

<h1>Last videos from <%= @tag.title %></h1>

<div class="row">
    <div class="col-md-12">
        <%= render partial: "youtube/video_player", locals: { video: sorted_videos.first } %>
    </div>
    <div class="col-md-12">
        <%= render partial: "youtube/videos", locals: { videos: sorted_videos } %>
    </div>
</div>