config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
    root 'static_pages#home'
  
    #Devise routes
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }
    
    resources :users, only: [:show, :index]
    resources :tags, only: [:index, :show, :create]
    resources :channels, only: [:index, :show]
    
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Youdeo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to users_path(), 'data-toggle': "tooltip", 'data-placement': "bottom", title: "See all users" do %>
              Users
            <% end %>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
          <li class="navbar-brand">
            <%= link_to user_path(current_user), 'data-toggle': "tooltip", 'data-placement': "bottom", title: "Go to your profile" do %>
              <%= image_tag current_user.google_image_url, class: "img-fluid rounded", width: "30px" if current_user.google_image_url %>
            <% end %>
          </li>
          
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <!--form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form-->
    </div>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Youdeo</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class="container-fluid">
      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>
      
      <%= yield %>  
    </div>
    
  </body>
</html>